# if you use SGE cluster, set the maximum number of jobs
sge_jobs: 10

# mRNA expression levles in GCT format.
# The 1st column must be gene symbols.
# Multiple files can be listed.
expression:
  - example/LUAD_n10.gct
