name: riboduct
channels:
  - r
  - bioconda
dependencies:
  - snakemake #=3.13.3
  - r-base #=3.4.1
  - r-dplyr #=0.7.0
  - r-data.table #=1.10.4
  - r-readr #=1.1.1
  - bioconductor-gsva #=1.26.0
  - r-rcurl
  - r-bit64

#  - pandas
